# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuopen = QtWidgets.QMenu(self.menu)
        self.menuopen.setObjectName("menuopen")
        self.menutools = QtWidgets.QMenu(self.menubar)
        self.menutools.setObjectName("menutools")
        self.menuview = QtWidgets.QMenu(self.menubar)
        self.menuview.setObjectName("menuview")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionimport_file = QtWidgets.QAction(MainWindow)
        self.actionimport_file.setObjectName("actionimport_file")
        self.actionprocess01 = QtWidgets.QAction(MainWindow)
        self.actionprocess01.setObjectName("actionprocess01")
        self.actionQgs_Project = QtWidgets.QAction(MainWindow)
        self.actionQgs_Project.setObjectName("actionQgs_Project")
        self.actioncsv = QtWidgets.QAction(MainWindow)
        self.actioncsv.setObjectName("actioncsv")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../userdata/Pictures/c#/放大.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoomIn.setIcon(icon)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../userdata/Pictures/c#/缩小.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoomOut.setIcon(icon1)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.menuopen.addAction(self.actionQgs_Project)
        self.menuopen.addAction(self.actioncsv)
        self.menu.addAction(self.menuopen.menuAction())
        self.menu.addAction(self.actionimport_file)
        self.menutools.addAction(self.actionprocess01)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuview.menuAction())
        self.menubar.addAction(self.menutools.menuAction())
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoomOut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "project"))
        self.menuopen.setTitle(_translate("MainWindow", "open"))
        self.menutools.setTitle(_translate("MainWindow", "tools"))
        self.menuview.setTitle(_translate("MainWindow", "layer view"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionimport_file.setText(_translate("MainWindow", "import file"))
        self.actionprocess01.setText(_translate("MainWindow", "process01"))
        self.actionQgs_Project.setText(_translate("MainWindow", "Qgs Project"))
        self.actioncsv.setText(_translate("MainWindow", "csv"))
        self.actionZoomIn.setText(_translate("MainWindow", "放大"))
        self.actionZoomOut.setText(_translate("MainWindow", "缩小"))
